# permissions for end users to edit nginies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginy-operator
    app.kubernetes.io/managed-by: kustomize
  name: nginy-editor-role
rules:
- apiGroups:
  - demo.example.com
  resources:
  - nginies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.example.com
  resources:
  - nginies/status
  verbs:
  - get
